package com.artplanapp.model.artplanuser;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "ArtPlanUserMaster")
public class ArtPlanUser {

    private String artPlanUserId;
    private String artPlanUserName;
    private String artPlanUserEmail;
    private String artPlanUserMobileNo;
    private String artPlanUserRating;

    @DynamoDBHashKey(attributeName = "artplanuser_id")
    @DynamoDBAutoGeneratedKey

    public String getArtPlanUserId() {
        return artPlanUserId;
    }

    public void setArtPlanUserId(String artPlanUserId) {
        this.artPlanUserId = artPlanUserId;
    }

    public String getArtPlanUserName() {
        return artPlanUserName;
    }

    public void setArtPlanUserName(String artPlanUserName) {
        this.artPlanUserName = artPlanUserName;
    }

    public String getArtPlanUserEmail() {
        return artPlanUserEmail;
    }

    public void setArtPlanUserEmail(String artPlanUserEmail) {
        this.artPlanUserEmail = artPlanUserEmail;
    }

    public String getArtPlanUserMobileNo() {
        return artPlanUserMobileNo;
    }

    public void setArtPlanUserMobileNo(String artPlanUserMobileNo) {
        this.artPlanUserMobileNo = artPlanUserMobileNo;
    }

    public String getArtPlanUserRating() {
        return artPlanUserRating;
    }

    public void setArtPlanUserRating(String artPlanUserRating) {
        this.artPlanUserRating = artPlanUserRating;
    }
}
